#!/usr/bin/env python3
"""Report and verify exhaustive Crowdin source classification."""

from collections import Counter
import argparse
import json
from pathlib import Path

from rangers.dat import DAT

from crowdin_sync import (
    ASSET_DIR,
    COVERAGE,
    GAME,
    LANG_DIR,
    QUEST_DIR,
    corpus_files,
    iter_strings,
    pointer,
    read_rows,
)


def audit() -> tuple[dict, dict]:
    coverage = json.loads(COVERAGE.read_text(encoding="utf-8"))
    entries = coverage["entries"]
    classified_dat = {
        row["identifier"] for row in entries if row["kind"] == "lang_dat"
    }
    source = DAT.from_dat(GAME / "CFG/Rus/Lang.dat").to_dict()
    source_dat = {pointer(path) for path, _ in iter_strings(source)}
    assert classified_dat == source_dat, "Some Lang.dat values are unclassified"

    rows = [row for path in corpus_files() for row in read_rows(path)]
    ids = [row["identifier"] for row in rows]
    assert len(ids) == len(set(ids)), "Duplicate Crowdin identifiers"

    by_kind = Counter(row["kind"] for row in entries)
    by_status = Counter((row["kind"], row["status"]) for row in entries)
    result = {
        "crowdin": {
            "files": len(corpus_files()),
            "rows": len(rows),
            "translated": sum(bool(row["be"]) for row in rows),
            "lang_dat_files": len(list(LANG_DIR.glob("*.tsv"))),
            "quest_files": len(list(QUEST_DIR.glob("*.tsv"))),
            "asset_files": len(list(ASSET_DIR.glob("*.tsv"))),
        },
        "coverage": {
            kind: {
                "total": by_kind[kind],
                "translatable": by_status[kind, "translatable"],
                "excluded": by_status[kind, "excluded"],
                "deferred": by_status[kind, "deferred"],
            }
            for kind in sorted(by_kind)
        },
    }
    return result, coverage


def markdown(result: dict, coverage: dict) -> str:
    crowdin = result["crowdin"]
    layers = result["coverage"]
    deferred_assets = sum(
        row.get("renderer") == "deferred"
        for row in coverage["entries"]
        if row["kind"] == "asset"
    )
    return f"""# Translation scope audit

Generated by `audit_translation_scope.py` from `crowdin/coverage.json`.

## Crowdin corpus

- **{crowdin['rows']:,}** player-facing source strings in **{crowdin['files']}** TSV files.
- **{crowdin['translated']:,}** existing Belarusian translations.
- `Lang.dat`: {layers['lang_dat']['translatable']:,} strings in {crowdin['lang_dat_files']} section files.
- Text quests: {layers['quest']['translatable']:,} fields in {crowdin['quest_files']} per-quest files.
- `robots.dat`: {layers['robots_dat']['translatable']:,} translatable property values.
- Baked assets: {layers['asset']['translatable']} known labels in {crowdin['asset_files']} form files.

## Exhaustive classification

| Layer | Total inspected | Translatable | Excluded |
|---|---:|---:|---:|
| Core `Lang.dat` | {layers['lang_dat']['total']:,} | {layers['lang_dat']['translatable']:,} | {layers['lang_dat']['excluded']:,} |
| QMM text fields | {layers['quest']['total']:,} | {layers['quest']['translatable']:,} | {layers['quest']['excluded']:,} |
| `robots.dat` properties | {layers['robots_dat']['total']:,} | {layers['robots_dat']['translatable']:,} | {layers['robots_dat']['excluded']:,} |
| Known baked labels | {layers['asset']['total']:,} | {layers['asset']['translatable']:,} | {layers['asset']['excluded']:,} |

Every inspected source path is listed in `crowdin/coverage.json` as
`translatable` or `excluded` with a reason. Classification uses Russian text,
the matching English localization, field semantics, and resource-path checks;
scripts, formulas, filenames, URLs, and empty values are not blindly exposed.

## Binary safety gates

- Both Eng/Rus `Lang.dat` files are rebuilt as signed `HDMain` DATs.
- All 80 Russian QMM files pass byte-identical parse/write no-op checks.
- `robots.dat` uses the MatrixGame `CStorage` (`STRG`/`ZL03`) format; its raw
  storage records pass a byte-identical no-op check before values are exposed.
- Seven menu labels are rendered into 21 GI button-state files.
- {deferred_assets} complex GI labels are represented in Crowdin but remain
  marked with the `deferred` renderer until specialized image reconstruction is
  implemented.

The checked-in corpus is the source of truth for Crowdin and the mod build.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    result, coverage = audit()
    print(json.dumps(result, ensure_ascii=False, indent=2))
    if args.write:
        path = Path(__file__).parent / "TRANSLATION-SCOPE.md"
        path.write_text(markdown(result, coverage), encoding="utf-8")
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
